services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: mykeycloak
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
    command: start-dev